[program:simok-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /Users/muhammadajirosyidsyailendra/PROJECTS/CODING/ABSystem/simok-webapp/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=muhammadajirosyidsyailendra
numprocs=2
redirect_stderr=true
stdout_logfile=/Users/muhammadajirosyidsyailendra/PROJECTS/CODING/ABSystem/simok-webapp/storage/logs/worker.log
stopwaitsecs=3600
